name: Publish Package
on: workflow_dispatch
jobs: 
  publish_nuget_package:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: |
          dotnet build ./ComtradeHandler.Core -c Release

      - name: Pack Project
        run: |
          dotnet pack ./ComtradeHandler.Core -c Release --no-build

      - name: Publish to Nuget
        env:
          NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
        run: |
          dotnet nuget push ./ComtradeHandler.Core/**/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json

      - name: Publish to Github
        run: |
          dotnet nuget add source --username gabrieldelaparra --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/gabrieldelaparra/index.json"
          dotnet nuget push ./ComtradeHandler.Core/**/*.nupkg --source "github"