name: Publish Package
on: workflow_dispatch
jobs: 
  publish_nuget_package:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Pack Project
        run: |
          dotnet pack ./ComtradeHandler.Core -c Release

      - name: Publish to Nuget
        env:
          NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
        run: |
          dotnet nuget push ./ComtradeHandler.Core/**/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json