name: Publish Package
on: workflow_dispatch
jobs: 
  publish_nuget_package:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Pack Project
        run: |
          dotnet pack ./ComtradeHanlder.Core -c Release

      - name: Publish
        env:
          NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
        run: |
          dotnet nuget push ./ComtradeHanlder.Core/**/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json